CREATE TABLE IF NOT EXISTS city (
  id INT(11) NOT NULL,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS customer (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(250) DEFAULT NULL,
  email VARCHAR(75) DEFAULT NULL,
  phone_number VARCHAR(63) NOT NULL,
  cityId INT(11) NOT NULL,
  zip_code VARCHAR(9) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=357 ;

CREATE TABLE IF NOT EXISTS product (
  id VARCHAR(15) NOT NULL,
  produto VARCHAR(255) NOT NULL,
  NCM INT(8) DEFAULT NULL,
  unidade_comercial_produto VARCHAR(255) NOT NULL,
  preco_comercial_produto FLOAT NOT NULL,
  unidade_tributavel_produto VARCHAR(255) NOT NULL,
  preco_tributavel_produto FLOAT NOT NULL,
  CFOP INT(4) NOT NULL DEFAULT '5405',
  CST INT(3) NOT NULL DEFAULT '60',
  origem INT(1) NOT NULL DEFAULT '0',
  situacao_tributaria INT(3) NOT NULL DEFAULT '60',
  regime INT(2) NOT NULL DEFAULT '3' COMMENT 'Verificar',
  PIS INT(2) NOT NULL DEFAULT '7',
  cofins INT(2) NOT NULL DEFAULT '7',
  cEan bigint(13) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS customer_product (
  id INT NOT NULL AUTO_INCREMENT,
  productId VARCHAR(15) NOT NULL,
  customerId INT(11) NOT NULL,

  PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;